from __future__ import annotations

from typing import Any, Protocol

class Session(Protocol):
    async def clear_cache(self) -> Any: ...
    async def trigger_message(self, requested_message: str, connector_id: int | None = None) -> Any: ...
    async def change_availability(self, connector_id: int, availability_type: str) -> Any: ...
    async def unlock_connector(self, connector_id: int) -> Any: ...
    async def remote_start(self, *, id_tag: str, connector_id: int | None = None) -> Any: ...
    async def remote_stop(self, transaction_id: int) -> Any: ...
    async def reset(self, reset_type: str = "Soft") -> Any: ...
    async def get_configuration(self, keys: list[str] | None = None) -> Any: ...
    async def change_configuration(self, key: str, value: str) -> Any: ...
    async def get_local_list_version(self) -> Any: ...
    async def send_local_list(self, list_version: int, entries: list[dict[str, Any]]) -> Any: ...
    async def set_charging_profile(self, connector_id: int, profile: dict[str, Any]) -> Any: ...
    async def clear_charging_profile(
        self,
        *,
        profile_id: int | None = None,
        connector_id: int | None = None,
        purpose: str | None = None,
        stack_level: int | None = None,
    ) -> Any: ...
    async def get_composite_schedule(
        self,
        connector_id: int,
        duration: int,
        charging_rate_unit: str | None = None,
    ) -> Any: ...


class SessionRegistry(Protocol):
    def session(self, charge_point_id: str) -> Session | None: ...
    def connected_chargers(self) -> list[str]: ...
    def physical_connector_ids(self, charge_point_id: str) -> list[int]: ...
    def active_transactions(self, charge_point_id: str) -> list[tuple[int, int | None]]: ...
    def active_transaction_ids(self, charge_point_id: str) -> list[int]: ...
    def record_control_event(self, event: str, *, charger_id: str, details: dict[str, Any] | None = None) -> None: ...
    def latest_rfid_list_version(self, charger_id: str) -> int | None: ...
    def record_rfid_list(
        self,
        charger_id: str,
        *,
        list_version: int,
        entries: list[dict[str, Any]],
        source_file: str | None,
        list_hash: str,
        verified_version: int | None,
    ) -> int: ...

